import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const karla = localFont({
  src: [
    { path: "./fonts/karla/Karla-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/karla/Karla-Medium.ttf", weight: "500", style: "normal" },
    { path: "./fonts/karla/Karla-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "./fonts/karla/Karla-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-karla",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${karla.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
